runtime: custom
env: flex

# Ensure that the service is always scaled to one instance
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1

# Set the entrypoint command to run the Node.js application
entrypoint: npm start
